Картитнки общественных мест
IngenerkaTeamNewYork/CityMap pull request #4
Opened 2017-09-30 13:33 UTC by SvyatkinYura

2017-09-30 13:46 UTC, nm17 requested changes
Убери пробелы.

2017-09-30 13:47 UTC, NeverMine17 commented
Сейчас исправлю.

2017-10-01 06:02 UTC, mabramovsd reviewed
Согласен с Даниилом. Лучше все названия файлов и папок без пробелов делать (PublicHouses, CarService.bmp и т.д.). Иначе (если криво написать код) компилятор может распознать car service.bmp как две строки

2017-10-04 10:16 UTC, nm17 approved these changes

2017-10-04 10:18 UTC, merged